language: python
python:
  - "3.5.6"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install colorlog
  - pip3 install homeassistant
script:
  - hass -c . --script check_config

