#
#  SENSORS
#

# QNAP NAS
- platform: qnap
  host: !secret nas_ip
  username: !secret nas_username
  password: !secret nas_password
  monitored_conditions:
    - status
    - cpu_usage
    - cpu_temp
    - memory_percent_used
    - network_tx
    - network_rx
    - volume_percentage_used
    - drive_smart_status
    - drive_temp

# System Monitors
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: load_5m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0

# Weather prediction
- platform: bom
  station: !secret my_bom_station
  name: !secret my_bom_name 
  monitored_conditions:
    - apparent_t
    - delta_t
    - rel_hum
    - air_temp
    - press
    - cloud
    - rain_trace
    - dewpt
    - wind_spd_kmh
    - wind_spd_kt
    - gust_kmh
    - gust_kt
    - wind_dir

# - platform: bom_forecast
#   product_id: !secret my_bom_product_id
#   name: !secret my_bom_name 
#   forecast_days: 6
#   rest_of_today: true
#   friendly: false
#   friendly_state_format: '{max}, {summary}'
#   monitored_conditions:
#     - 'max'
#     - 'min'
#     - 'chance_of_rain'
#     - 'possible_rainfall'
#     - 'summary'
#     - 'detailed_summary'
#     - 'icon'

# Pi Hole DNS

#- platform: pi_hole
#  host: localhost:4865
#  monitored_conditions:
#    - ads_blocked_today
#    - ads_percentage_today
#    - dns_queries_today
#     - unique_clients

# Time Functions
- platform: time_date
  display_options:
    - 'date'
- platform: template
  sensors:
    week:
      friendly_name: Week Number
      value_template: >-
        {{ strptime(states('sensor.date'), '%Y-%m-%d').strftime('%V') }}
